### ISSUE TITLE
GPS acquisition module error

### ISSUE THREAD

**Issue by FayeWong98** [Mortarboard-H/GPS-Receiver-SDR-on-GNURadio#1]
Hello, I created a file in gnuradio according to your pictures, but the connecting lines at the left and right ends of the GPS acquisition module are red. Can you answer this question for me? Version 3.8

**Comment by Mortarboard-H** [comment]
You must have chosen the wrong input and output type.  The input to stream_to_vector should be complex32. Red lines in gnuradio always refers to wrong data type.

**Comment by FayeWong98** [comment]
I can confirm that the data type of all modules is complex. This is my flowchart. I don't know what went wrong. I hope you can help me solve it, or can you provide GRC files?

**Comment by FayeWong98** [comment]
<img width="676" alt="20220811102717" src="https://user-images.githubusercontent.com/39408976/184055182-a5b6d919-4ac7-409c-85b7-53ebe6284371.png">

**Comment by FayeWong98** [comment]
Hello, I have solved this problem, but the input makes me very confused. Is PRN the GPS satellite number (1-32)? How do I know the value of PRN in advance to input parameters without analysis; In addition, is there any specific connection between vectorlen and samprate?

In addition, after I import the GPS source file, I run the program and find that the console output is Nan. Can this GRC file import only one captured satellite data;

I look forward to your reply!

**Comment by Mortarboard-H** [comment]
this module is designed just to test if there is signal of certain satellite. You can imagine it as one channel of a receiver. you can create 32 blocks as 32 channels. Vectorlen is the number of samples in 1ms, the period of PRN.  
"In addition, after I import the GPS source file, I run the program and find that the console output is Nan. Can this GRC file import only one captured satellite data;"
As for this, have you tried with only one source file?  Does that work properly?

**Comment by FayeWong98** [comment]
Thank you for your answer. I noticed that this project is to complete the functions of integrated acquisition and capture. I look forward to your follow-up supplement. Or are there other GNSS projects based on gnuradio that can be recommended? thank you!

**Comment by Mortarboard-H** [comment]
"Or are there other GNSS projects based on gnuradio that can be recommended? thank you!"
Please refer to GNSS-SDR https://github.com/gnss-sdr/gnss-sdr

**Comment by Imprimtive** [comment]
could you tell me  how to resolve the same issue that the lines red?

**Comment by FayeWong98** [comment]
I'm sorry to tell you that I haven't paid attention to this project for a long time. In my impression, the data format may be adjusted, and the specific code of the flow diagram does not need to be changed. That's all I can think of, hope it helps.

**Comment by Imprimtive** [comment]
thank for your reply, I  have checked all blocks' data format and make sure that all of them are cmplex64 just same as the code of python block, but it still red and its error message shows that the IO size doesn't match, so I don't know how to resolve this problem. Or are there other GPS receive projects based on gnuradio that can be recommended? thank you!

**Comment by FayeWong98** [comment]
I recommend to study the GNS-SDR project, which includes the receiving and decoding process of the four major navigation satellite systems. I hope this project can help you. If you want to discuss further, you can leave your contact information.

**Comment by Imprimtive** [comment]
thank you for your help, I am fresh man in navigation satellite systems. So maybe I need more help, and its my email address: 1219692984@qq.com , and recently , I am learning to build a GPS software simulator based on GNU ,so if you have some advice I will so glad to receive your email!

**Comment by FayeWong98** [comment]
I have a general understanding. I don't know much about GNU-based GPS software simulators, so it may be difficult to help you. But I feel that GNSS-SDR can give you a lot of help, or there are other better reference projects? good luck to you!
